CREATE DATABASE EcommerceDB;
GO

/*===========================================================
Project 3 : E-Commerce SQL Analytics & Business Intelligence

Tools Used:
- SQL Server Management Studio (SSMS)
- SQL

Objective:
Analyze customer behavior, sales performance,
payment trends and order status using SQL queries.

===========================================================*/

USE EcommerceDB;
GO

/*===========================================================
1. DATA OVERVIEW
Understanding the size of the dataset
===========================================================*/

-- Total number of orders-1200

SELECT COUNT(*) AS TotalOrders
FROM Orders;

-- Total number of unique customers-1189

SELECT COUNT(DISTINCT CustomerID) AS UniqueCustomers
FROM Orders;

-- Preview dataset

SELECT TOP 10 *
FROM Orders;


/*===========================================================
2. REVENUE ANALYSIS
Understanding overall business performance
===========================================================*/

-- Total revenue generated

SELECT SUM(TotalPrice) AS TotalRevenue
FROM Orders;

-- Average order value

SELECT AVG(TotalPrice) AS AverageOrderValue
FROM Orders;

-- Highest order value

SELECT MAX(TotalPrice) AS HighestOrderValue
FROM Orders;

-- Lowest order value

SELECT MIN(TotalPrice) AS LowestOrderValue
FROM Orders;


/*===========================================================
3. PRODUCT ANALYSIS
Identifying top-performing products
===========================================================*/

-- Products with highest quantity sold

SELECT
    Product,
    SUM(Quantity) AS QuantitySold
FROM Orders
GROUP BY Product
ORDER BY QuantitySold DESC;

-- Products generating highest revenue

SELECT
    Product,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY Product
ORDER BY RevenueGenerated DESC;

-- Number of orders per product

SELECT
    Product,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY Product
ORDER BY TotalOrders DESC;


/*===========================================================
4. CUSTOMER ANALYSIS
Understanding customer contribution
===========================================================*/

-- Top 10 customers by revenue

SELECT TOP 10
    CustomerID,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY CustomerID
ORDER BY RevenueGenerated DESC;

-- Customers with most orders

SELECT TOP 10
    CustomerID,
    COUNT(*) AS OrdersPlaced
FROM Orders
GROUP BY CustomerID
ORDER BY OrdersPlaced DESC;


/*===========================================================
5. PAYMENT METHOD ANALYSIS
Finding preferred payment options
===========================================================*/

-- Most used payment methods

SELECT
    PaymentMethod,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY PaymentMethod
ORDER BY TotalOrders DESC;

-- Revenue generated by each payment method

SELECT
    PaymentMethod,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY PaymentMethod
ORDER BY RevenueGenerated DESC;


/*===========================================================
6. ORDER STATUS ANALYSIS
Tracking completed and cancelled orders
===========================================================*/

-- Distribution of order status

SELECT
    OrderStatus,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY OrderStatus
ORDER BY TotalOrders DESC;

-- Cancellation count

SELECT
    COUNT(*) AS CancelledOrders
FROM Orders
WHERE OrderStatus = 'Cancelled';


/*===========================================================
7. REFERRAL SOURCE ANALYSIS
Understanding customer acquisition channels
===========================================================*/

-- Orders by referral source

SELECT
    ReferralSource,
    COUNT(*) AS OrdersReceived
FROM Orders
GROUP BY ReferralSource
ORDER BY OrdersReceived DESC;

-- Revenue by referral source

SELECT
    ReferralSource,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY ReferralSource
ORDER BY RevenueGenerated DESC;


/*===========================================================
8. COUPON ANALYSIS
Evaluating coupon usage
===========================================================*/

-- Most frequently used coupons

SELECT
    CouponCode,
    COUNT(*) AS UsageCount
FROM Orders
WHERE CouponCode IS NOT NULL
GROUP BY CouponCode
ORDER BY UsageCount DESC;


/*===========================================================
9. SHOPPING BEHAVIOR ANALYSIS
Understanding cart behavior
===========================================================*/

-- Average items per cart

SELECT
    AVG(ItemsInCart) AS AvgItemsPerCart
FROM Orders;

-- Maximum items in cart

SELECT
    MAX(ItemsInCart) AS MaxItemsInCart
FROM Orders;


/*===========================================================
10. MONTHLY SALES TREND
Understanding business growth over time
===========================================================*/

-- Monthly revenue trend

SELECT
    YEAR([Date]) AS Year,
    MONTH([Date]) AS Month,
    SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY YEAR([Date]), MONTH([Date])
ORDER BY Year, Month;

-- Monthly order volume

SELECT
    YEAR([Date]) AS Year,
    MONTH([Date]) AS Month,
    COUNT(*) AS Orders
FROM Orders
GROUP BY YEAR([Date]), MONTH([Date])
ORDER BY Year, Month;


/*===========================================================
12. PRODUCT REVENUE CONTRIBUTION (CTE)
===========================================================*/

WITH ProductRevenue AS
(
    SELECT
        Product,
        SUM(TotalPrice) AS Revenue
    FROM Orders
    GROUP BY Product
)

SELECT
    Product,
    Revenue,
    ROUND((Revenue * 100.0) /
        (SELECT SUM(Revenue) FROM ProductRevenue),2)
        AS RevenuePercentage
FROM ProductRevenue
ORDER BY Revenue DESC;

/*===========================================================
13. CUSTOMER RANKING
===========================================================*/

SELECT
    CustomerID,
    SUM(TotalPrice) AS Revenue,
    RANK() OVER
    (
        ORDER BY SUM(TotalPrice) DESC
    ) AS CustomerRank
FROM Orders
GROUP BY CustomerID;

/*===========================================================
14. RUNNING TOTAL REVENUE
===========================================================*/

WITH MonthlyRevenue AS
(
SELECT
YEAR(Date) AS Year,
MONTH(Date) AS Month,
SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY YEAR(Date),MONTH(Date)
)

SELECT *,
SUM(Revenue)
OVER
(
ORDER BY Year,Month
ROWS BETWEEN UNBOUNDED PRECEDING
AND CURRENT ROW
)
AS RunningRevenue
FROM MonthlyRevenue;


/*===========================================================
15. MONTH-OVER-MONTH REVENUE
===========================================================*/

WITH MonthlyRevenue AS
(
SELECT
YEAR(Date) AS Year,
MONTH(Date) AS Month,
SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY YEAR(Date),MONTH(Date)
)

SELECT
*,
LAG(Revenue)
OVER
(
ORDER BY Year,Month
)
AS PreviousMonthRevenue
FROM MonthlyRevenue;


/*===========================================================
16. MONTHLY GROWTH %
===========================================================*/

WITH MonthlyRevenue AS
(
SELECT
YEAR(Date) AS Year,
MONTH(Date) AS Month,
SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY YEAR(Date),MONTH(Date)
)

SELECT
*,
LAG(Revenue)
OVER(ORDER BY Year,Month)
AS PreviousRevenue,

ROUND(

(
Revenue-
LAG(Revenue)
OVER(ORDER BY Year,Month)

)

*100.0/

LAG(Revenue)
OVER(ORDER BY Year,Month)

,2)

AS GrowthPercent

FROM MonthlyRevenue;




/*===========================================================
17. CUSTOMER SEGMENTATION
===========================================================*/

SELECT
CustomerID,
SUM(TotalPrice) AS Revenue,

CASE

WHEN SUM(TotalPrice)>=5000 THEN 'High Value'

WHEN SUM(TotalPrice)>=2500 THEN 'Medium Value'

ELSE 'Low Value'

END AS CustomerSegment

FROM Orders

GROUP BY CustomerID

ORDER BY Revenue DESC;


/*===========================================================
18. HIGHEST REVENUE ORDER PER PRODUCT
===========================================================*/

WITH RankedOrders AS
(
SELECT
Product,
OrderID,
CustomerID,
TotalPrice,

ROW_NUMBER()
OVER
(
PARTITION BY Product
ORDER BY TotalPrice DESC
)
AS rn

FROM Orders
)

SELECT *
FROM RankedOrders
WHERE rn=1;


/*===========================================================
19. TOP 3 CUSTOMERS PER PRODUCT
===========================================================*/

WITH RankedCustomers AS
(
SELECT
Product,
CustomerID,
SUM(TotalPrice) AS Revenue,

DENSE_RANK()
OVER
(
PARTITION BY Product
ORDER BY SUM(TotalPrice) DESC
)
AS Ranking

FROM Orders

GROUP BY Product,CustomerID
)

SELECT *
FROM RankedCustomers
WHERE Ranking<=3;


/*===========================================================
20. ABOVE AVERAGE ORDERS
===========================================================*/

SELECT *
FROM Orders

WHERE TotalPrice>

(
SELECT AVG(TotalPrice)
FROM Orders
)

ORDER BY TotalPrice DESC;


/*===========================================================
21. CANCELLATION RATE
===========================================================*/

SELECT

COUNT(CASE WHEN OrderStatus='Cancelled' THEN 1 END)
AS CancelledOrders,

COUNT(*) AS TotalOrders,

ROUND(

COUNT(CASE WHEN OrderStatus='Cancelled' THEN 1 END)

*100.0

/

COUNT(*)

,2)

AS CancellationRate;

/*===========================================================
11. BUSINESS INSIGHTS

The SQL analysis answers the following business questions:

1. What is the total revenue generated?
2. Which products generate the highest revenue?
3. Which products have the highest sales volume?
4. Who are the top revenue-generating customers?
5. Which payment methods are most frequently used?
6. Which payment methods contribute the highest revenue?
7. Which referral sources drive the most customers?
8. Which referral sources generate the highest revenue?
9. What is the average order value?
10. How does monthly revenue change over time?
11. Which products contribute the largest percentage of total revenue?
12. Who are the highest-ranked customers based on revenue?
13. What is the cumulative (running) revenue over time?
14. How does monthly revenue compare with the previous month?
15. What is the month-over-month revenue growth percentage?
16. How can customers be segmented into High, Medium, and Low Value groups?
17. What is the highest-value order for each product?
18. Who are the top three customers for every product?
19. Which orders have values above the overall average order value?
20. What is the overall cancellation rate of customer orders?

Advanced SQL Concepts Demonstrated:
- Common Table Expressions (CTEs)
- Window Functions (ROW_NUMBER, RANK, DENSE_RANK, LAG)
- CASE Expressions
- Aggregate Functions
- Subqueries
- Running Totals
- Customer Segmentation
- Business KPI Analysis

===========================================================*/



