CREATE DATABASE EcommerceDB;
GO

/*===========================================================
Project 3 : E-Commerce SQL Analytics & Business Intelligence

Tools Used:
- SQL Server Management Studio (SSMS)
- SQL

Objective:
Analyze customer behavior, sales performance,
payment trends and order status using SQL queries.

===========================================================*/

USE EcommerceDB;
GO

/*===========================================================
1. DATA OVERVIEW
Understanding the size of the dataset
===========================================================*/

-- Total number of orders-1200

SELECT COUNT(*) AS TotalOrders
FROM Orders;

-- Total number of unique customers-1189

SELECT COUNT(DISTINCT CustomerID) AS UniqueCustomers
FROM Orders;

-- Preview dataset

SELECT TOP 10 *
FROM Orders;


/*===========================================================
2. REVENUE ANALYSIS
Understanding overall business performance
===========================================================*/

-- Total revenue generated

SELECT SUM(TotalPrice) AS TotalRevenue
FROM Orders;

-- Average order value

SELECT AVG(TotalPrice) AS AverageOrderValue
FROM Orders;

-- Highest order value

SELECT MAX(TotalPrice) AS HighestOrderValue
FROM Orders;

-- Lowest order value

SELECT MIN(TotalPrice) AS LowestOrderValue
FROM Orders;


/*===========================================================
3. PRODUCT ANALYSIS
Identifying top-performing products
===========================================================*/

-- Products with highest quantity sold

SELECT
    Product,
    SUM(Quantity) AS QuantitySold
FROM Orders
GROUP BY Product
ORDER BY QuantitySold DESC;

-- Products generating highest revenue

SELECT
    Product,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY Product
ORDER BY RevenueGenerated DESC;

-- Number of orders per product

SELECT
    Product,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY Product
ORDER BY TotalOrders DESC;


/*===========================================================
4. CUSTOMER ANALYSIS
Understanding customer contribution
===========================================================*/

-- Top 10 customers by revenue

SELECT TOP 10
    CustomerID,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY CustomerID
ORDER BY RevenueGenerated DESC;

-- Customers with most orders

SELECT TOP 10
    CustomerID,
    COUNT(*) AS OrdersPlaced
FROM Orders
GROUP BY CustomerID
ORDER BY OrdersPlaced DESC;


/*===========================================================
5. PAYMENT METHOD ANALYSIS
Finding preferred payment options
===========================================================*/

-- Most used payment methods

SELECT
    PaymentMethod,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY PaymentMethod
ORDER BY TotalOrders DESC;

-- Revenue generated by each payment method

SELECT
    PaymentMethod,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY PaymentMethod
ORDER BY RevenueGenerated DESC;


/*===========================================================
6. ORDER STATUS ANALYSIS
Tracking completed and cancelled orders
===========================================================*/

-- Distribution of order status

SELECT
    OrderStatus,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY OrderStatus
ORDER BY TotalOrders DESC;

-- Cancellation count

SELECT
    COUNT(*) AS CancelledOrders
FROM Orders
WHERE OrderStatus = 'Cancelled';


/*===========================================================
7. REFERRAL SOURCE ANALYSIS
Understanding customer acquisition channels
===========================================================*/

-- Orders by referral source

SELECT
    ReferralSource,
    COUNT(*) AS OrdersReceived
FROM Orders
GROUP BY ReferralSource
ORDER BY OrdersReceived DESC;

-- Revenue by referral source

SELECT
    ReferralSource,
    SUM(TotalPrice) AS RevenueGenerated
FROM Orders
GROUP BY ReferralSource
ORDER BY RevenueGenerated DESC;


/*===========================================================
8. COUPON ANALYSIS
Evaluating coupon usage
===========================================================*/

-- Most frequently used coupons

SELECT
    CouponCode,
    COUNT(*) AS UsageCount
FROM Orders
WHERE CouponCode IS NOT NULL
GROUP BY CouponCode
ORDER BY UsageCount DESC;


/*===========================================================
9. SHOPPING BEHAVIOR ANALYSIS
Understanding cart behavior
===========================================================*/

-- Average items per cart

SELECT
    AVG(ItemsInCart) AS AvgItemsPerCart
FROM Orders;

-- Maximum items in cart

SELECT
    MAX(ItemsInCart) AS MaxItemsInCart
FROM Orders;


/*===========================================================
10. MONTHLY SALES TREND
Understanding business growth over time
===========================================================*/

-- Monthly revenue trend

SELECT
    YEAR([Date]) AS Year,
    MONTH([Date]) AS Month,
    SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY YEAR([Date]), MONTH([Date])
ORDER BY Year, Month;

-- Monthly order volume

SELECT
    YEAR([Date]) AS Year,
    MONTH([Date]) AS Month,
    COUNT(*) AS Orders
FROM Orders
GROUP BY YEAR([Date]), MONTH([Date])
ORDER BY Year, Month;


/*===========================================================
11. BUSINESS INSIGHTS
Key questions answered:

1. What is the total revenue generated?
2. Which products generate the most revenue?
3. Which products sell the highest quantity?
4. Who are the top customers?
5. Which payment method is most preferred?
6. What is the cancellation count?
7. Which referral source brings most customers?
8. Which referral source generates maximum revenue?
9. What is the average order value?
10. How does revenue change month by month?

===========================================================*/

